### ISSUE TITLE
.getChilds() function not calling back, but is throwing error

### ISSUE THREAD

**Issue by Andrew-Gallimore** [DablioZe/SecureDB#3]
Hello!

I am having issues with the "getChilds()" function, and am unable to figure out what the solution to the issue is. For context, I am running this in a server, in an updated version of Node with secure-db version 1.5.1. And the server is inside a wrapper of NW.js to create a desktop app out of my program.

Actively, I am calling the function (by following the docs provided in this repository):
```
db.getChilds('server', function( server_list ) {
    console.log(server_list);
});
```
But it is simply throwing an error saying:
> Uncaught TypeError: Failed to execute the 'getChilds' function: The second argument cannot be different from a function.

To troubleshoot, I have tested (and made some headway, kinda) by calling:
```
db.getChilds('server', testing());
function testing(server_list) {
    console.log(server_list);
}
```
And at least it was throwing a different error:    \\( '-' )/
> Uncaught SyntaxError: Failed to execute the 'getChilds' function: missing arguments.

But even if I write it with different formatting:
```
db.getChilds('server', server_list => {
    console.log(server_list);
}
```
Still the error about the second argument not being a function persists.

I would love to hear from you about what error I am making (because I feel like it will be a case of a stupid mistake on my part). :D 
Or if the case is, which is why I am coming to you, there is an issue with the package/library, I can provide what ever you need to help figure this out.

Thank you for this amazing library!

**Comment by DablioZe** [comment]
Hey!

I noticed the problem you had so I did several tests here, I asked developer friends to perform similar tests to see if it returns the error of your problem but none did.

The source code for this package is old. The last time it was updated, it used an outdated version of node. For this reason, I would imagine a lack of package update could be causing this issue.

I am preparing a new version of this package. This release will have some very important changes so I ask that you read the documentation when it becomes available. I rebuilt the package completely from scratch, all functions were tested and all errors found were fixed.

If this issue persists, the error is most likely in your code. Can you share with me the code block that is causing this problem so that I can analyze and see if I can find the problem.

I apologize in advance, I'm super willing to help you solve this problem. The new update will be released no later than 5/22/22 - 11:59PM

**Comment by Andrew-Gallimore** [comment]
Thank you for the speedy response,

Here is a large chunk of my code from the JavaScript file causing the issues, with some comments around it :)
```
// Import and run the Express Node web server framework
var express = require('express');
var app = express();

// Point it to the directory as a static server
app.use(express.static('src/public'));

// Listen on port 3000 for any traffic
app.listen(3000);

console.log("server active");

// Importing secure database to store graphics and data
const db = require('secure-db');


const sMain = new db.Child('server', 'main');
const sGraphics = new db.Child('server', 'graphics');

sGraphics.set("account", {
    graphicsID: "9a7svcq2oivhbqaei7"
})
console.log(sGraphics.get('account')); //  <<< this works

// vvv The rest below doesn't work. (And the line right below this is line 112) vvv
db.getChilds('server', function( params ) {
    console.log(params);
});
// db.getChilds('server', testing());
// function testing(params) {
//     console.log(params)
// }
// db.getChilds('server', user_list => {
//     console.log(user_list)
// })
```
And the full error I am seeing through DevTools is:
> Uncaught TypeError: Failed to execute the 'getChilds' function: The second argument cannot be different from a function.
    at Object.dataMustBeFunction (C:\Users\HP\Main\Coding\Live_Control_Board\NWjs\RXTX_Studio-1.4\node_modules\secure-db\lib\Errors.js:12:16)
    at Database.getChilds (C:\Users\HP\Main\Coding\Live_Control_Board\NWjs\RXTX_Studio-1.4\node_modules\secure-db\lib\index.js:129:65)
    at chrome-extension://hchfipaabhjoalojakeeiaffhmommnae/src/server/js/server.js:112:4


Keep in mind that this JavaScript is loaded/running from an HTML file that has access to node through NW.js. I am using the API way of developing with NW.js, so it acts as a regular dependency from NPM (in the package.json) which loads the HTML page in a desktop window. Considering that no one else was able to reproduce the result means that it might be something to do with the JavaScript being ran through NW.js, or it's just something with my code.

Node versions I tested with:
- v14.17.6
- v16.15.0 (after I updated trying to see if that would help)

If you need anything else, feel free to ask. I will be looking forward to the new version of this package, and I am impressed with your willingness to help, but don't rush too much. My project that is using this library isn't going to be finished tomorrow, so don't worry too much about getting it out immediately. :D

**Comment by DablioZe** [comment]
![image](https://user-images.githubusercontent.com/63757378/169718499-7cbd440d-fc88-4f2f-b2df-1c13166a5252.png)
I ran your code in a normal development environment, using the same version of the package you indicated. Almost all the functions worked without any errors, only one gave an error and this one has the wrong syntax

```js
db.getChilds('server', testing());
function testing(params) {
    console.log(params)
}
```
In order for the "testing" function to be used as a callback, you need to remove the parentheses from `testing()` because as it stands you are calling the testing function and executing it before the `getChilds` function takes action and as the function `testing` doesn't return anything, it would look like this `db.getChild('server', undefined)`;

Anyway, I released a new [package update](https://github.com/secure-db/secure-db). This update makes some important changes to the `Child` and `getChilds` functions and as you use these functions you need to look at the [changes](https://github.com/secure-db/secure-db#deprecated-functions-important) before updating in your project.

For better development, the github repository for this package has been migrated to https://github.com/secure-db.

I hope I helped you with your problem, if the problem persists, come back to talk to me.

**Comment by DablioZe** [comment]
It's actually quite strange that the package doesn't recognize the function you've entered as an actual function, I can't think of a reason for that.
Just in case, I changed this way of checking the callback function, you can [check here](https://github.com/secure-db/secure-db/commit/179823217d4a4d35f59d5cefda73e23bd20342b8). It's the way you said it works for you. If it still doesn't work, it's probably some incompatibility with the `NW.js` you're using. I will study this `NW.js` package to understand it and find out if there is any incompatibility so I can fix it.

[The new version of the package.](https://github.com/secure-db/secure-db)
